openapi: "3.0.0"
info:
  version: '0.0.1'
  title: QueerGlobal Artwork API
  description: An api for Artwork data in the QueerGlobal system
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://queerglobal.com/api
paths:
  /healthcheck:
    get:
      summary: Healthcheck for this API
      description: Healthcheck for server status
      operationId: InternalHealthCheck
      responses:
        '200':
          description: Response to healthchecks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthCheckResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /artwork/{id}:
    get:
      summary: Returns an artwork by ID
      description: Returns an artwork based on a single ID
      operationId: FindArtworkById
      parameters:
        - name: id
          in: path
          description: ID of artwork to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: artwork response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artwork'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Deletes an artwork by ID
      description: deletes a single artwork based on the ID supplied
      operationId: delete artwork
      parameters:
        - name: id
          in: path
          description: ID of artwork to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: artwork deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update an artwork
      description: Updates artwork. Duplicates are allowed
      operationId: UpdateArtwork
      parameters:
        - name: id
          in: path
          description: ID of artwork to delete
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Artwork to update to the page
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artwork'
      responses:
        '200':
          description: artwork
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artwork'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /artwork:
    post:
      summary: Creates a new artwork
      description: Creates a new artwork. Duplicates are allowed
      operationId: AddArtwork
      requestBody:
        description: Artwork to add to the page
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artwork'
      responses:
        '200':
          description: artwork
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artwork'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Returns artwork based on query string
      description: Returns artwork based on query strings
      operationId: FindArtworks
      parameters:
        - name: userName          
          in: query
          description: ID of user to fetch
          required: false
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: artwork response
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Artwork'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    HealthCheckResponse:
      type: object
      required: 
        - status
        - serviceName
      properties: 
        status: 
          type: string
        serviceName:
          type: string


    ArtworkType:
      required:
        - artworkTypeID
        - artworkTypeName
      properties:
        artworkTypeID:
          type: integer
          format: int64
        artworkTypeName:
          type: integer
          format: int64


    Artwork:
      required:
        - artworkType
        - ownerPersonID
      properties:
        artworkID:
          type: integer
          format: int64
        artworkType:
          type: object
          $ref: '#/components/schemas/ArtworkType'
        ownerPersonID:
          type: number
          format: int64
        chips: 
          type: array
          items:
            $ref: '#/components/schemas/Chip'


    Chip:
      required:
        - value
      properties:
        id:
          type: number
          format: int64
        value:
          type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
          description: Error code
        message:
          type: string
          description: Error message
