openapi: "3.0.0"
info:
  version: '0.0.1'
  title: QueerGlobal Locations API
  description: An api for Location data in the QueerGlobal system
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://queerglobal.com/api
paths:
  /healthcheck:
    get:
      summary: Healthcheck for this API
      description: Healthcheck for server status
      operationId: InternalHealthCheck
      responses:
        '200':
          description: Response to healthchecks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthCheckResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /member/{id}:
    get:
      summary: Returns a member by ID
      description: Returns a member based on a single ID
      operationId: FindLocationById
      parameters:
        - name: id
          in: path
          description: ID of member to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: member response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Deletes a member by ID
      description: deletes a single member based on the ID supplied
      operationId: delete member
      parameters:
        - name: id
          in: path
          description: ID of member to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: member deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a member
      description: Updates member. Duplicates are allowed
      operationId: UpdateLocation
      parameters:
        - name: id
          in: path
          description: ID of member to delete
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Location to update to the page
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /member:
    post:
      summary: Creates a new member
      description: Creates a new member. Duplicates are allowed
      operationId: AddLocation
      requestBody:
        description: Location to add to the page
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Returns member based on query string
      description: Returns member based on query strings
      operationId: FindLocations
      parameters:
        - name: userName          
          in: query
          description: ID of user to fetch
          required: false
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: member response
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Location'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    HealthCheckResponse:
      type: object
      required: 
        - status
        - serviceName
      properties: 
        status: 
          type: string
        serviceName:
          type: string

    Location:
      required:
        - StreetAddressLines
        - Country
        - AdministrativeArea
        - Locality
        - Latitude
        - Longitude
      properties:
        StreetAddressLines:
          type: string
          description: Street Address Lines combined into a single field
        Country:
          type: string
          description: Country Code
        AdminstrativeArea:
          type: string
          description: Adminstrative Area (in US, for example, a State)
        Locality:
          type: string
          description: Tha name of the locality. In the US, the city or town
        Lat:
          type: number
          description: Degrees latitude of the location
        Long:
          type: number
          description: Degrees longitude of the location

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
          description: Error code
        message:
          type: string
          description: Error message
